### Get all ads
GET http://localhost:8080/ads
Content-Type: application/json

### Get avatar
GET http://localhost:8080/avatars/e02f3a7a-1a5a-4f60-bf73-ee2cda304ce2.jpg
Content-Type: application/octet-stream

### Get image for ad
GET http://localhost:8080/images/cc5c5d96-ddce-479c-aa2d-9a4b42576f0f.jpg
Content-Type: application/octet-stream

### Create a new ad
POST http://localhost:8080/ads
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic user2@gmail.com user2@gmail.com

--WebAppBoundary
Content-Disposition: form-data; name="properties"
Content-Type: application/json

{
  "price": 6000,
  "title": "New title7",
  "description": "New content7"
}

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="mto.jpg"
Content-Type: image/jpeg

< mto.jpg

### Get ad by id
GET http://localhost:8080/ads/33
Content-Type: application/json
Authorization: Basic user2@gmail.com user2@gmail.com

### Delete ad by id
DELETE http://localhost:8080/ads/32
Content-Type: application/json
Authorization: Basic user2@gmail.com user2@gmail.com

### Update ad by id
PATCH http://localhost:8080/ads/33
Content-Type: application/json
Authorization: Basic user2@gmail.com user2@gmail.com

{
  "price": 50000,
  "title": "!!!Some new user4@gmail.com",
  "description": "!!!Some new content user4@gmail.com"
}

### Get all ads by autorized user
GET http://localhost:8080/ads/me
Content-Type: application/json
Authorization: Basic user2@gmail.com user2@gmail.com

### Update an image for ad
PATCH http://localhost:8080/ads/31/image
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic user2@gmail.com user2@gmail.com

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="mto.jpg"
Content-Type: image/jpeg

< mto.jpg

### Get comments for ad
GET http://localhost:8080/ads/14/comments
Content-Type: application/json
Authorization: Basic user2@gmail.com user2@gmail.com

### Add comment to ad
POST http://localhost:8080/ads/14/comments
Content-Type: application/json
Authorization: Basic user2@gmail.com user2@gmail.com

{
  "text": "Comment text to Ad #14"
}

### Update comment for ad
PATCH http://localhost:8080/ads/14/comments/12
Content-Type: application/json
Authorization: Basic user3@gmail.com user3@gmail.com

{
  "text": "Updated Comment text user33333@gmail.com"
}

### Delete comment for ad
DELETE http://localhost:8080/ads/12/comments/13
Content-Type: application/json
Authorization: Basic user3@gmail.com user3@gmail.com

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user7@gmail.com",
  "password": "user7@gmail.com"
}

### Register
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "user7@gmail.com",
  "password": "user7@gmail.com",
  "firstName": "User7",
  "lastName": "Dummy7",
  "phone": "+7 (913) 213-55-57",
  "role": "USER"
}

### Get details of an authenticated user
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic user1@gmail.com user1@gmail.com

### Update details of an authenticated user
PATCH http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic user1@gmail.com user1@gmail.com

{
  "phone": "+7 (913) 213-55-57",
  "firstName": "Dennis77",
  "lastName": "Carolunas77"
}

### Change password of an authenticated user
POST http://localhost:8080/users/set_password
Content-Type: application/json
Authorization: Basic user7@gmail.com user7@gmail.com

{
  "newPassword": "user7@gmail.com",
  "currentPassword": "newPassword"
}

### Update an avatar for an authenticated user
PATCH http://localhost:8080/users/me/image
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic administrator@gmail.com administrator

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="mto.jpg"
Content-Type: image/jpeg

< mto.jpg