#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.datasource.url= jdbc:postgresql://localhost:5432/diplomchik
spring.datasource.username=postgres
spring.datasource.password=679459ryt

spring.jpa.properties.hibernate.hbm2ddl.jdbc_metadata_extraction_strategy=individually
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

avatar.dir.path=src/main/java/ru/skypro/homework/images
ad.image.path=src/main/java/ru/skypro/homework/ad_image